// @ts-nocheck -- skip type checking
import * as d_docs_8 from "../content/docs/integrations/tanstackstart.mdx?collection=docs"
import * as d_docs_7 from "../content/docs/integrations/nextjs.mdx?collection=docs"
import * as d_docs_6 from "../content/docs/auth/GoogleOAuth.mdx?collection=docs"
import * as d_docs_5 from "../content/docs/auth/GithubOAuth.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/auth/forgetPassword.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/auth/credentials.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/(root)/installation.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/(root)/index.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/(root)/changelog.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"(root)/changelog.mdx","fullPath":"content\\docs\\(root)\\changelog.mdx"}, data: d_docs_0 }, { info: {"path":"(root)/index.mdx","fullPath":"content\\docs\\(root)\\index.mdx"}, data: d_docs_1 }, { info: {"path":"(root)/installation.mdx","fullPath":"content\\docs\\(root)\\installation.mdx"}, data: d_docs_2 }, { info: {"path":"auth/credentials.mdx","fullPath":"content\\docs\\auth\\credentials.mdx"}, data: d_docs_3 }, { info: {"path":"auth/forgetPassword.mdx","fullPath":"content\\docs\\auth\\forgetPassword.mdx"}, data: d_docs_4 }, { info: {"path":"auth/GithubOAuth.mdx","fullPath":"content\\docs\\auth\\GithubOAuth.mdx"}, data: d_docs_5 }, { info: {"path":"auth/GoogleOAuth.mdx","fullPath":"content\\docs\\auth\\GoogleOAuth.mdx"}, data: d_docs_6 }, { info: {"path":"integrations/nextjs.mdx","fullPath":"content\\docs\\integrations\\nextjs.mdx"}, data: d_docs_7 }, { info: {"path":"integrations/tanstackstart.mdx","fullPath":"content\\docs\\integrations\\tanstackstart.mdx"}, data: d_docs_8 }], [{"info":{"path":"meta.json","fullPath":"content\\docs\\meta.json"},"data":{"pages":["auth","integrations"],"root":true}}, {"info":{"path":"(root)/meta.json","fullPath":"content\\docs\\(root)\\meta.json"},"data":{"title":"Get Started","pages":["index","installation"],"root":false}}, {"info":{"path":"auth/meta.json","fullPath":"content\\docs\\auth\\meta.json"},"data":{"title":"Auth","pages":["credentials","forgetPassword","GoogleOAuth","GithubOAuth"]}}, {"info":{"path":"integrations/meta.json","fullPath":"content\\docs\\integrations\\meta.json"},"data":{"title":"Integrations","pages":["nextjs","tanstackstart"]}}])